services:
  spring-app:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      args:
        DATE: ${DATE}
        JAR_NAME: ${JAR_NAME}
    ports:
      - ${CONTAINER_PORT}:${CONTAINER_PORT}
