package com.quangnv.msb.configuration.api;

public enum ApiAction {
    LOGIN,
    LOGOUT,
    FORGOT_PASSWORD,
    GET_TRANSACTION,
    GET_TRANSACTION_BY_ID,
    SUM_AMOUNT_TRANSACTION,
    STATISTIC_TRANSACTION,
    GET_VA,
    GET_VA_BY_ID,
    GET_USER_DETAIL,
    UPDATE_USER,
    GET_ACTIONS,
    FIND_TERMINALS_BY_MID,
    GET_TERMINAL_BY_ID,
    RESET_PASSWORD,
    CHANGE_PASSWORD,
    GET_NTF_SETTING,
    UPDATE_NTF_SETTING,
    FIND_USER_BY_FILTER
}
